apiVersion: apps/v1
kind: Deployment
metadata:
  name: openai-assistant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openai-assistant
  template:
    metadata:
      labels:
        app: openai-assistant
    spec:
      containers:
        - name: openai-assistant
          image: gcr.io/alamo-utec/openai_assistant_flask:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"  
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key
                  key: OPENAI_API_KEY
            - name: ASSISTANT_ID
              valueFrom:
                secretKeyRef:
                  name: assistant-id
                  key: ASSISTANT_ID 
