apiVersion: v1
kind: Service
metadata:
  name: openai-assistant-service
spec:
  type: LoadBalancer
  selector:
    app: openai-assistant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
